pull_request_rules:
  - name: automatic merge for master when CI passes
    conditions:
      - "status-success=build-and-test"
      - base=master
      - label!=work-in-progress
    actions:
      merge:
        method: merge
