require: rubocop-rails
# see the documentation for this file: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - config/**/*
    - bin/**/*
Layout/HashAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/LinkToBlank:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues :
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

# It is ok to not create timestamps for table creation
Rails/CreateTableWithTimestamps:
  Enabled: false

# Allow to use drop_table within migrations w/o restoring information.
Rails/ReversibleMigration:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - test
    - development
    - production
