version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "web"
    tty: true
    stdin_open: true
    volumes:
      - .:/my_project
    networks:
      - my_projcet_net
    ports:
      - "3000:3000"
    links:
      - sidekiq
      - postgres
      - redis
    environment:
      - RAILS_ENV=development
  sidekiq:
    build: .
    command: bundle exe sidekiq -C config/sidekiq.yml
    container_name: "my_project_sidekiq"
    tty: true
    stdin_open: true
    volumes:
      - .:/my_project
    networks:
      - my_projcet_net
    links:
      - postgres
      - redis
  postgres:
    image: camptocamp/postgres:9.6
    container_name: "my_project_postgres"
    networks:
      - my_projcet_net
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  redis:
    image: redis
    container_name: "my_project_redis"
    networks:
      - my_projcet_net
    ports:
      - "6379:6379"
volumes:
  my_projcet_vol:
  db-data:
networks:
  my_projcet_net:
